### ISSUE TITLE
Add release info in the metadata json file

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#11]
As of now we are not adding the release info to the metadata file which we should add like `v4.1.0-rc` .

**Comment by cfergeau** [comment]
I'm considering dealing with #11 and #12 in a similar way, by using a git tag. For issue #11, if the current commit matches a signed tag with name '4.1.0-rc.1', then we'll get "sncVersion": "4.1.0-rc.1" in the bundle info file, rather than the "gitxxxx" we get for other commits.
For #12, if the current commit corresponds to a '4.1.0-rc.1' git tag, then we can name the directory crc_libvirt_4.1.0-rc.1 rather than using a date based name. And we can also use it to automatically set OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE

**Comment by cfergeau** [comment]
This was fixed in PR #15
