### ISSUE TITLE
Add OKD/OCP info in the bundle metadata

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#237]
We are now generating bundle for OCP and OKD better to have that info in the bundle metadata also.

**Comment by anjannath** [comment]
maybe this can be part of the `clusterInfo` object?

```js
"clusterInfo": {
    "openshiftVarient":"okd or ocp",
    "openshiftVersion": "4.1.11 or 4.5.0-0.okd-2020-10-03-012432",
    "clusterName": "crc",
[...]
}
```

**Comment by guillaumerose** [comment]
What if we don't do it ? I would like to avoid to have in CRC a lot of `if okd then`, `if ocp then`. 

Currently we would need it for:
* having the correct oc client
* asking or not for the pull secret.

For oc, we can directly add it in the bundle. It makes sense to have the client next to the bundle since they are coming from the same source.

For the pull secret, we could add in the bundle an optional default pull secret. For OKD, it would be a placeholder. For OCP, it won't be provided and CRC will then ask for it.
It enables a "feature" for large deployment of CRC in the same company: IT dep. can repackage a bundle with a pull secret, it avoids end users to have to sign in on Red Hat portal.

**Comment by anjannath** [comment]
> What if we don't do it ? I would like to avoid to have in CRC a lot of if okd then, if ocp then.

We can still identify the bundle, only from the `openshiftVersion`, but have to do some string matching.

> For the pull secret, we could add in the bundle an optional default pull secret. For OKD, it would be a placeholder. For OCP, it won't be provided and CRC will then ask for it.

For this we'll need to know if its an okd bundle or ocp bundle to be able to make the choice between using or not using the default pull secret from the bundle meta data.

but we can avoid the check for getting the `oc`, which is already better.

**Comment by cfergeau** [comment]
> We can still identify the bundle, only from the openshiftVersion, but have to do some string matching.

I've already asked to avoid this if possible as this is bound to break sooner or later.

> For this we'll need to know if its an okd bundle or ocp bundle to be able to make the choice between using or not using the default pull secret from the bundle meta data.

The check would be "is there a pull secret in the bundle or not?"

With an OKD bundle, we probably should not be showing in the UI `OpenShift version: xxx` but `OKD version: xxx` because OKD is *not* OpenShift (which is a Red Hat product/trademark). Dunno how strongly PM/... would care about this.

For debugging purpose imo it's always good to have a log telling us whether it's OKD or OpenShift even if this could be guessed from the versioning.

**Comment by cgruver** [comment]
For what it's worth, OKD contains tons of references to OpenShift.

For example:

```bash
Authentication required for https://api.okd4.clg.lab:6443 (openshift)
Username: admin
Password: 
Login successful.

You have access to 63 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
```

The UI, in a full OKD install, still refers to `OpenShift version`.  The pages bear the OKD logo instead of OpenShift, but all of the internals are still OpenShift.

**Comment by praveenkumar** [comment]
I think now using snc we can create both the bundles (okd/ocp), we still force user to provide pull secret path and in case of okd user can provide and dummy/empty pull secret as mention in readme file.
