### ISSUE TITLE
Add podman client in the bundle

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/snc#318]
A bundle contains an image of the OpenShift cluster + the oc client of the exact same version. We could do the same for podman. It will ensure the client is always compatible with the server.

We would then ship podman 2.0.5 and not 3.0. This is sad, but we don't have the choice if we want to ship something usable.
OKD might ship version 3.0.

**Comment by cfergeau** [comment]
We did something similar in the past, but podman backward/forward compatibility was not so great, and this ended up causing issues. The problem was something like 'do stuff with podman, then install crc which gives you an older/newer podman -> some things break'. Maybe it  has improved since then, but something to be careful with.

**Comment by gbraad** [comment]
we can ship 2.0.6, but thsi is related to the issue I filed at Podman: https://github.com/containers/podman/issues/9098Scott would always want we can use 'any' client that the user has installed. and he talked about v2 being compatible for this?
