### ISSUE TITLE
kernel command line argument should be taken after installing any packages and performing a reboot

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#80]
https://github.com/code-ready/crc/issues/420 was caused because we installed the hyperV packages which change the ostree. Since we didn't rebooted the system it doesn't switch the ostree and caused this issue. We need to either get that kernel line args before or reboot the system and then get it.

**Comment by cfergeau** [comment]
I don't think getting the kernel commandline before package installation will help. We either need to build it from `ostree admin status`, or reboot after installing the hyperv packages. I'd go with the latter.

**Comment by praveenkumar** [comment]
@cfergeau I didn't check before creating the issue looks like we are already get the kernel cmdline https://github.com/code-ready/snc/blob/master/createdisk.sh#L248-L249 before even install the packages https://github.com/code-ready/snc/blob/master/createdisk.sh#L261-L262 which means issue is somewhere else. I will take closer look.

**Comment by cfergeau** [comment]
Getting the command line before installing the packages is wrong, as installing the packages will:
- create a new ostree hash so that it's possible to get a tree with the packages installed
- (I think) trigger a switch between boot.0 and boot.1 on next reboot so that the new tree is picked

We want the new tree to be picked as the one before installing the packages will not contain the newly installed packages. So we need to install the packages, reboot, and finally get the kernel command line.

**Comment by praveenkumar** [comment]
> Getting the command line before installing the packages is wrong, as installing the packages will:

@cfergeau Right, new tree is anyway picked in case of libvirt and hyperv or VB since when next reboot happens it will happen on the latest tree, problem is only with hyperkit since it need kernel cmdline which is different than the rebooted system. so we do need to do a reboot and then get the kernel cmdline.

**Comment by praveenkumar** [comment]
fixed by #81
